apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- mongo-express.yaml

images:
  - name: repo.lab/expresscart
    newTag: 1.0.3

# Development namespace
namespace: expresscart-dev

# Generate the secret for mongoExpress admin login
secretGenerator:
- name: mongoexpress-login
  literals:
  - username=admin
  - password=admin
generatorOptions:
  disableNameSuffixHash: true
  labels:
    type: generated
  annotations:
    note: generated

# Update namespace of claimRef as PersistentVolumeClaim
replacements:
- source:
    fieldPath: metadata.namespace
    name: nfs-db-pvc
    kind: PersistentVolumeClaim
  targets:
  - select:
      kind: PersistentVolume
      name: nfs-db-pv
    fieldPaths:
    - spec.claimRef.namespace
