apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- path: ingress-production.yaml

# Or specific in which component to replace
#patches:
#- target: 
#      group: networking.k8s.io
#      version: v1
#      kind: Ingress
#      name: expresscart-ingress
#   path: ingress-production.yaml

images:
  - name: repo.lab/expresscart
    newTag: 1.0.2

# Production namespace
namespace: expresscart

# Update namespace of claimRef as PersistentVolumeClaim
replacements:
- source:
    fieldPath: metadata.namespace
    name: nfs-db-pvc
    kind: PersistentVolumeClaim
  targets:
  - select:
      kind: PersistentVolume
      name: nfs-db-pv
    fieldPaths:
    - spec.claimRef.namespace
