{
 "title": "Synology NAS Details Dashboard for Prometheus",
 "description": "群晖NAS详细仪表板",
 "tags": [
  "synology",
  "snmp_exporter",
  "prometheus"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "NASDevices", "query": "${VAR_NASDEVICES}" },
   { "name": "interfacebits", "query": "8" },
   { "name": "JobName", "label": "Job Name", "query": { "query": "label_values(ssCpuUser, job)" } },
   {
    "name": "Device",
    "query": {
     "query": "query_result(ssCpuUser{job=~'$JobName'})"
    }
   },
   {
    "name": "Interface",
    "query": {
     "query": "label_values(ifName{job=~'$JobName',instance=~'$Device'},ifName)"
    }
   },
   {
    "name": "InterfacePhysical",
    "label": "Network Interface",
    "query": {
     "query": "label_values(ifOperStatus{job=~\"$JobName\", instance=~\"$Device\"},ifName)"
    }
   },
   {
    "name": "InterfaceVirtual",
    "label": "Virtual Interfaces",
    "query": {
     "query": "label_values(ifType_info{job=~'$JobName',instance=~'$Device'},ifName)"
    }
   },
   {
    "name": "DiskName",
    "label": "Disk",
    "query": {
     "query": "label_values(diskID{job=~'$JobName',instance=~'$Device'},diskID)"
    }
   },
   {
    "name": "DiskNameSSD",
    "label": "Cache",
    "query": {
     "query": "label_values(diskID{job=~'$JobName',instance=~'$Device'},diskID)"
    }
   },
   {
    "name": "raidName",
    "label": "Storage",
    "query": {
     "query": "label_values(raidName{job=~'$JobName',instance=~'$Device'},raidName)"
    }
   },
   {
    "name": "storageIODevice",
    "label": "Disk",
    "query": {
     "query": "label_values(storageIODevice{job=~'$JobName',instance=~'$Device'},storageIODevice)"
    }
   },
   {
    "name": "spaceIODevice",
    "label": "Volume Name",
    "query": {
     "query": "label_values(spaceIODevice{job=~'$JobName',instance=~'$Device'},spaceIODevice)"
    }
   },
   {
    "name": "hrStorageDescr",
    "label": "File System",
    "query": {
     "query": "label_values(hrStorageDescr{job=~'$JobName',instance=~'$Device'},hrStorageDescr)"
    }
   },
   {
    "name": "flashCacheDisk",
    "label": "Cache",
    "query": {
     "query": "label_values(flashCacheSSDDev{job=~'$JobName',instance=~'$Device'},flashCacheSSDDev)"
    }
   },
   {
    "name": "hrMemoryDescr",
    "label": "Memory",
    "query": {
     "query": "label_values(hrStorageDescr{job=~'$JobName',instance=~'$Device'},hrStorageDescr)"
    }
   },
   {
    "name": "SmartDev",
    "label": "S.M.A.R.T",
    "query": {
     "query": "label_values(diskSMARTInfoDevName{job=~'$JobName',instance=~'$Device'},diskSMARTInfoDevName)"
    }
   },
   {
    "name": "services",
    "query": {
     "query": "label_values(serviceName{job=~'$JobName',instance=~'$Device'},serviceName)"
    }
   }
  ]
 },
 "panels": [
  { "title": "系统状态 - ($Device)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "群晖系统信息 - $Device",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "hrSystemUptime{job=~'$JobName',instance=~'$Device'} / 86400",
     "legendFormat": "uptime"
    },
    {
     "expr": "upgradeAvailable{job=~'$JobName',instance=~'$Device'}"
    },
    {
     "expr": "temperature{job=~'$JobName',instance=~'$Device'}"
    },
    {
     "expr": "cpuFanStatus{job=~'$JobName',instance=~'$Device'}"
    },
    {
     "expr": "systemFanStatus{job=~'$JobName',instance=~'$Device'}"
    },
    {
     "expr": "systemStatus{job=~'$JobName',instance=~'$Device'}"
    },
    {
     "expr": "powerStatus{job=~'$JobName',instance=~'$Device'}"
    },
    {
     "expr": "modelName{job=~'$JobName',instance=~'$Device'}"
    },
    {
     "expr": "version{job=~'$JobName',instance=~'$Device'}"
    },
    {
     "expr": "serialNumber{job=~'$JobName',instance=~'$Device'}"
    },
    {
     "expr": "memTotalReal{job=~'$JobName',instance=~'$Device'}"
    },
    {
     "expr": "count(diskIndex{job=~'$JobName',instance=~'$Device',diskID=~'$DiskName'})"
    }
   ]
  },
  {
   "title": "群晖系统",
   "type": "stat",
   "description": "在 NASDevices 变量中输入您正在监控的 Synology 设备数量。正数表示有设备掉线或无法获取数据，负数表示系统收集的数据源多于 NASDevices 变量中设定的设备数量。",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "count(systemStatus)", "legendFormat": "Total Synology's" },
    {
     "expr": "$NASDevices-count(systemStatus)",
     "legendFormat": "Synology's Down"
    },
    {
     "expr": "count(systemStatus)-$NASDevices",
     "legendFormat": "Update NAS variable"
    }
   ]
  },
  {
   "title": "网络接口状态",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(ifAdminStatus{job=~'$JobName',instance=~'$Device',ifName=~'$InterfacePhysical'} == 1)",
     "legendFormat": "Admin Up"
    },
    {
     "expr": "count(ifAdminStatus{job=~'$JobName',instance=~'$Device',ifName=~'$InterfacePhysical'} == 2)",
     "legendFormat": "Admin Down"
    },
    {
     "expr": "(count(ifOperStatus{job=~'$JobName',instance=~'$Device',ifName=~'$InterfacePhysical'} == 2 )) - (count(ifAdminStatus{job=~'$JobName',instance=~'$Device',ifName=~'$InterfacePhysical'} == 2 ))",
     "legendFormat": "DOWN"
    }
   ]
  },
  {
   "title": "存储卷",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(raidStatus{job=~'$JobName',instance=~'$Device',raidName=~'$raidName'})",
     "legendFormat": "Total Volumes"
    },
    {
     "expr": "count((raidStatus{job=~'$JobName',instance=~'$Device',raidName=~'$raidName'}>=2 and raidStatus{job=~'$JobName',instance=~'$Device',raidName=~'$raidName'}<=10) or (raidStatus{job=~'$JobName',instance=~'$Device',raidName=~'$raidName'}>=13 and {job=~'$JobName',instance=~'$Device',raidName=~'$raidName'}<=20))",
     "legendFormat": "RAID Warning"
    },
    {
     "expr": "count((raidStatus{job=~'$JobName',instance=~'$Device',raidName=~'$raidName'}>=11 and raidStatus{job=~'$JobName',instance=~'$Device',raidName=~'$raidName'}<=12) or raidStatus{job=~'$JobName',instance=~'$Device',raidName=~'$raidName'}>21)",
     "legendFormat": "RAID Failure"
    }
   ]
  },
  {
   "title": "硬盘",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(diskIndex{job=~'$JobName',instance=~'$Device',diskID=~'$DiskName'})",
     "legendFormat": "Total Drives"
    },
    {
     "expr": "count(diskStatus{job=~'$JobName',instance=~'$Device',diskID=~'$DiskName'}>=2) and count(diskStatus{job=~'$JobName',instance=~'$Device',diskID=~'$DiskName'}<=3)",
     "legendFormat": "Not Used"
    },
    {
     "expr": "count(diskStatus{job=~'$JobName',instance=~'$Device',diskID=~'$DiskName'}>=4)",
     "legendFormat": "Failure"
    }
   ]
  },
  {
   "title": "缓存盘",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(diskIndex{job=~'$JobName',instance=~'$Device',diskID=~'$DiskNameSSD'})",
     "legendFormat": "Total Drives"
    },
    {
     "expr": "count(diskStatus{job=~'$JobName',instance=~'$Device',diskID=~'$DiskNameSSD'}==3)",
     "legendFormat": "Not Used"
    },
    {
     "expr": "count(diskStatus{job=~'$JobName',instance=~'$Device',diskID=~'$DiskNameSSD'}>=4)",
     "legendFormat": "Failure"
    }
   ]
  },
  {
   "title": "S.M.A.R.T 状态",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(diskSMARTAttrStatus{job=~'$JobName',instance=~'$Device'} ==1)",
     "legendFormat": "SMART Checks"
    },
    {
     "expr": "count(diskSMARTAttrStatus{job=~'$JobName',instance=~'$Device',diskSMARTAttrStatus!=\"OK\"} ==1)",
     "legendFormat": "SMART Failures"
    }
   ]
  },
  {
   "title": "系统资源 - ($Device)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU 使用率 - ($Device)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "ssCpuUser{job=~'$JobName',instance=~'$Device'} + ssCpuSystem{job=~'$JobName',instance=~'$Device'}",
       "legendFormat": "Used"
      },
      {
       "expr": "100-(ssCpuUser{job=~'$JobName',instance=~'$Device'} + ssCpuSystem{job=~'$JobName',instance=~'$Device'})",
       "legendFormat": "Idle"
      }
     ]
    },
    {
     "title": "内存使用率 - ($Device)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(memTotalReal{job=~'$JobName',instance=~'$Device'} - (memAvailReal{job=~'$JobName',instance=~'$Device'} + memCached{job=~'$JobName',instance=~'$Device'} + memBuffer{job=~'$JobName',instance=~'$Device'})) / memTotalReal{job=~'$JobName',instance=~'$Device'}",
       "legendFormat": "Used"
      },
      {
       "expr": "1-((memTotalReal{job=~'$JobName',instance=~'$Device'} - (memAvailReal{job=~'$JobName',instance=~'$Device'} + memCached{job=~'$JobName',instance=~'$Device'} + memBuffer{job=~'$JobName',instance=~'$Device'})) / memTotalReal{job=~'$JobName',instance=~'$Device'})",
       "legendFormat": "Free"
      }
     ]
    },
    {
     "title": "CPU 利用率 - ($Device)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "ssCpuSystem{job=~'$JobName',instance=~'$Device'}",
       "legendFormat": "System"
      },
      {
       "expr": "ssCpuUser{job=~'$JobName',instance=~'$Device'}",
       "legendFormat": "User"
      },
      {
       "expr": "ssCpuIdle{job=~'$JobName',instance=~'$Device'}",
       "legendFormat": "Idle"
      }
     ]
    },
    {
     "title": "物理内存 - ($Device)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "expr": "memTotalReal{job=~'$JobName',instance=~'$Device'} ",
       "legendFormat": "Size"
      },
      {
       "expr": "memTotalReal{job=~'$JobName',instance=~'$Device'} - (memShared{job=~'$JobName',instance=~'$Device'} + memCached{job=~'$JobName',instance=~'$Device'} + memBuffer{job=~'$JobName',instance=~'$Device'} + memAvailReal{job=~'$JobName',instance=~'$Device'})",
       "legendFormat": "Reserved"
      },
      {
       "expr": "memBuffer{job=~'$JobName',instance=~'$Device'}",
       "legendFormat": "Buffer"
      },
      {
       "expr": "memCached{job=~'$JobName',instance=~'$Device'}",
       "legendFormat": "Cached"
      },
      {
       "expr": "memShared{job=~'$JobName',instance=~'$Device'}",
       "legendFormat": "Shared"
      },
      {
       "expr": "memAvailReal{job=~'$JobName',instance=~'$Device'}",
       "legendFormat": "Free"
      }
     ]
    },
    {
     "title": "CPU 负载 - ($Device)",
     "type": "timeseries",
     "description": "CPU 1分钟，5分钟，15分钟的负载情况",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "laLoadInt{job=~'$JobName',instance=~'$Device'}/100",
       "legendFormat": "{{laNames}}"
      }
     ]
    },
    {
     "title": "虚拟内存 - ($Device)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "expr": "memTotalReal{job=~'$JobName',instance=~'$Device'} + memTotalSwap{job=~'$JobName',instance=~'$Device'}",
       "legendFormat": "Size"
      },
      {
       "expr": "(memTotalReal{job=~'$JobName',instance=~'$Device'} + memTotalSwap{job=~'$JobName',instance=~'$Device'}) - memTotalFree{job=~'$JobName',instance=~'$Device'}",
       "legendFormat": "Used"
      },
      {
       "expr": "memTotalFree{job=~'$JobName',instance=~'$Device'}",
       "legendFormat": "Free"
      }
     ]
    },
    {
     "title": "进程数 - ($Device)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "hrSystemProcesses{job=~'$JobName',instance=~'$Device'}",
       "legendFormat": "进程"
      }
     ]
    },
    {
     "title": "用户数 / 服务 - ($Device)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "serviceUsers{job=~'$JobName',instance=~'$Device',serviceName=~'$services'}",
       "legendFormat": "{{serviceName}}"
      }
     ]
    }
   ]
  },
  {
   "title": "系统内部 - ($Device)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "网络接口 - ($Device)",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "ifPhysAddress{job=~'$JobName',instance=~'$Device',ifName=~'$Interface'}"
      },
      {
       "expr": "ifAdminStatus{job=~'$JobName',instance=~'$Device',ifName=~'$Interface'}"
      },
      {
       "expr": "ifHighSpeed{job=~'$JobName',instance=~'$Device',ifName=~'$Interface'}"
      },
      {
       "expr": "ifOperStatus{job=~'$JobName',instance=~'$Device',ifName=~'$Interface'}"
      },
      {
       "expr": "ifMtu{job=~'$JobName',instance=~'$Device',ifName=~'$Interface'}"
      }
     ]
    },
    {
     "title": "硬盘  - ($Device)",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "diskTemperature{job=~'$JobName',instance=~'$Device'}"
      },
      {
       "expr": "diskType{job=~'$JobName',instance=~'$Device'}"
      },
      {
       "expr": "diskStatus{job=~'$JobName',instance=~'$Device'}"
      },
      {
       "expr": "diskModel{job=~'$JobName',instance=~'$Device'}"
      }
     ]
    },
    {
     "title": "Bond/虚拟网络接口信息",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "ifPhysAddress{job=~'$JobName',instance=~'$Device',ifName=~'$InterfaceVirtual'}"
      },
      {
       "expr": "ifAdminStatus{job=~'$JobName',instance=~'$Device',ifName=~'$InterfaceVirtual'}"
      },
      {
       "expr": "ifHighSpeed{job=~'$JobName',instance=~'$Device',ifName=~'$InterfaceVirtual'}"
      },
      {
       "expr": "ifOperStatus{job=~'$JobName',instance=~'$Device',ifName=~'$InterfaceVirtual'}"
      },
      {
       "expr": "ifAlias{job=~'$JobName',instance=~'$Device',ifName=~'$InterfaceVirtual'}"
      },
      {
       "expr": "ifMtu{job=~'$JobName',instance=~'$Device',ifName=~'$InterfaceVirtual'}"
      }
     ]
    }
   ]
  },
  {
   "title": "存储: $raidName - ($Device)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "repeat": "raidName",
   "collapsed": true,
   "panels": [
    {
     "title": "RAID 状态",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "raidStatus{job=~'$JobName',instance=~'$Device',raidName=~'$raidName'}"
      }
     ]
    },
    {
     "title": "存储使用情况 - $raidName ($Device)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 21, "x": 3, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "raidTotalSize{job='$JobName',instance='$Device',raidName='$raidName'}",
       "legendFormat": "Size"
      },
      {
       "expr": "(raidTotalSize{job='$JobName',instance='$Device',raidName='$raidName'}-raidFreeSize{job='$JobName',instance='$Device',raidName='$raidName'})",
       "legendFormat": "Used"
      },
      {
       "expr": "raidFreeSize{job='$JobName',instance='$Device',raidName='$raidName'}",
       "legendFormat": "Free"
      }
     ]
    },
    {
     "title": "存储容量",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "raidTotalSize{job=~'$JobName',instance=~'$Device',raidName=~'$raidName'}"
      }
     ]
    },
    {
     "title": "已用空间百分比",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "((raidTotalSize{job=~'$JobName',instance=~'$Device',raidName=~'$raidName'}-raidFreeSize{job=~'$JobName',instance=~'$Device',raidName=~'$raidName'})/raidTotalSize{job=~'$JobName',instance=~'$Device',raidName=~'$raidName'})*100",
       "legendFormat": "% Free"
      }
     ]
    }
   ]
  },
  {
   "title": "文件系统: $hrStorageDescr ($Device)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "repeat": "hrStorageDescr",
   "collapsed": true,
   "panels": [
    {
     "title": "文件系统分区容量",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hrStorageSize{job=~'$JobName',instance=~'$Device',hrStorageDescr=~'$hrStorageDescr'} * hrStorageAllocationUnits{job=~'$JobName',instance=~'$Device',hrStorageDescr=~'$hrStorageDescr'}"
      }
     ]
    },
    {
     "title": "文件系统分区使用情况: $hrStorageDescr ($Device)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 21, "x": 3, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "hrStorageSize{job=~'$JobName',instance=~'$Device',hrStorageDescr=~'$hrStorageDescr'} * hrStorageAllocationUnits{job=~'$JobName',instance=~'$Device',hrStorageDescr=~'$hrStorageDescr'}",
       "legendFormat": "Size"
      },
      {
       "expr": "hrStorageUsed{job=~'$JobName',instance=~'$Device',hrStorageDescr=~'$hrStorageDescr'} * hrStorageAllocationUnits{job=~'$JobName',instance=~'$Device',hrStorageDescr=~'$hrStorageDescr'}",
       "legendFormat": "Used"
      },
      {
       "expr": "(hrStorageSize{job=~'$JobName',instance=~'$Device',hrStorageDescr=~'$hrStorageDescr'} -  hrStorageUsed{job=~'$JobName',instance=~'$Device',hrStorageDescr=~'$hrStorageDescr'}) * hrStorageAllocationUnits{job=~'$JobName',instance=~'$Device',hrStorageDescr=~'$hrStorageDescr'}\n",
       "legendFormat": "Free"
      }
     ]
    },
    {
     "title": "已用空间百分比",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(hrStorageUsed{job=~'$JobName',instance=~'$Device',hrStorageDescr=~'$hrStorageDescr'} /hrStorageSize{job=~'$JobName',instance=~'$Device',hrStorageDescr=~'$hrStorageDescr'})*100",
       "legendFormat": "% Used"
      }
     ]
    }
   ]
  },
  {
   "title": "HDD/SSD数据盘: $storageIODevice - ($Device)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "repeat": "storageIODevice",
   "collapsed": true,
   "panels": [
    {
     "title": "读取/写入字节数: $storageIODevice - ($Device)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "rate(storageIONReadX{job=~'$JobName',instance=~'$Device',storageIODevice=~'$storageIODevice'}[$__rate_interval])",
       "legendFormat": "Read Bits"
      },
      {
       "expr": "rate(storageIONWrittenX{job=~'$JobName',instance=~'$Device',storageIODevice=~'$storageIODevice'}[$__rate_interval])",
       "legendFormat": "Write Bits"
      }
     ]
    },
    {
     "title": "负载: $storageIODevice - ($Device)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "rate(storageIOLA{job=~'$JobName',instance=~'$Device',storageIODevice=~'$storageIODevice'}[$__rate_interval])",
       "legendFormat": "load"
      },
      {
       "expr": "rate(storageIOLA1{job=~'$JobName',instance=~'$Device',storageIODevice=~'$storageIODevice'}[$__rate_interval])",
       "legendFormat": "load 1 min avg"
      },
      {
       "expr": "rate(storageIOLA5{job=~'$JobName',instance=~'$Device',storageIODevice=~'$storageIODevice'}[$__rate_interval])",
       "legendFormat": "load 5 min avg"
      },
      {
       "expr": "rate(storageIOLA15{job=~'$JobName',instance=~'$Device',storageIODevice=~'$storageIODevice'}[$__rate_interval])",
       "legendFormat": "load 15  min avg"
      }
     ]
    },
    {
     "title": "读写 I/O: $storageIODevice - ($Device)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(storageIOReads{job=~'$JobName',instance=~'$Device',storageIODevice=~'$storageIODevice'}[$__rate_interval])",
       "legendFormat": "Read I/O"
      },
      {
       "expr": "irate(storageIOWrites{job=~'$JobName',instance=~'$Device',storageIODevice=~'$storageIODevice'}[$__rate_interval])",
       "legendFormat": "Write I/O"
      }
     ]
    }
   ]
  },
  {
   "title": "SSD缓存盘: $flashCacheDisk - ($Device)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "repeat": "flashCacheDisk",
   "collapsed": true,
   "panels": [
    {
     "title": "Bytes Read/Write: $flashCacheDisk- ($Device)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 155 },
     "targets": [
      {
       "expr": "rate(flashCacheDiskRead{job=~'$JobName',instance=~'$Device',flashCacheSSDDev=~'$flashCacheDisk'}[$__rate_interval])",
       "legendFormat": "Read Bytes"
      },
      {
       "expr": "rate(flashCacheDiskWrite{job=~'$JobName',instance=~'$Device',flashCacheSSDDev=~'$flashCacheDisk'}[$__rate_interval])",
       "legendFormat": "Written Bytes"
      }
     ]
    },
    {
     "title": "Read/Write Hits: $flashCacheDisk- ($Device)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 155 },
     "targets": [
      {
       "expr": "rate(flashCacheReadHits{job=~'$JobName',instance=~'$Device',flashCacheSSDDev=~'$flashCacheDisk'}[$__rate_interval])",
       "legendFormat": "Read Hits"
      },
      {
       "expr": "rate(flashCacheWriteHits{job=~'$JobName',instance=~'$Device',flashCacheSSDDev=~'$flashCacheDisk'}[$__rate_interval])",
       "legendFormat": "Write Hits"
      }
     ]
    },
    {
     "title": "Read/Write Total: $flashCacheDisk- ($Device)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 161 },
     "targets": [
      {
       "expr": "rate(flashCacheTotalRead{job=~'$JobName',instance=~'$Device',flashCacheSSDDev=~'$flashCacheDisk'}[$__rate_interval])",
       "legendFormat": "Total Read Hits"
      },
      {
       "expr": "rate(flashCacheTotalWrite{job=~'$JobName',instance=~'$Device',flashCacheSSDDev=~'$flashCacheDisk'}[$__rate_interval])",
       "legendFormat": "Total Write Hits"
      }
     ]
    },
    {
     "title": "Read/Write Hit Rate: $flashCacheDisk- ($Device)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 161 },
     "targets": [
      {
       "expr": "rate(flashCacheReadHitRate{job=~'$JobName',instance=~'$Device',flashCacheSSDDev=~'$flashCacheDisk'}[$__rate_interval])",
       "legendFormat": "Read Hit Rate"
      },
      {
       "expr": "rate(flashCacheWriteHitRate{job=~'$JobName',instance=~'$Device',flashCacheSSDDev=~'$flashCacheDisk'}[$__rate_interval])",
       "legendFormat": "Write Hit Rate"
      }
     ]
    },
    {
     "title": "Read/Write Skips: $flashCacheDisk- ($Device)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 167 },
     "targets": [
      {
       "expr": "rate(flashCacheReadSeqSkip{job=~'$JobName',instance=~'$Device',flashCacheSSDDev=~'$flashCacheDisk'}[$__rate_interval])",
       "legendFormat": "Read Skips"
      },
      {
       "expr": "rate(flashCacheWriteSeqSkip{job=~'$JobName',instance=~'$Device',flashCacheSSDDev=~'$flashCacheDisk'}[$__rate_interval])",
       "legendFormat": "Write Skips"
      }
     ]
    },
    {
     "title": "Write Misses: $flashCacheDisk- ($Device)",
     "type": "timeseries",
     "description": "The number of\ndata writes to SSD\nfor the first time",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 167 },
     "targets": [
      {
       "expr": "rate(flashCacheWriteMissSsd{job=~'$JobName',instance=~'$Device',flashCacheSSDDev=~'$flashCacheDisk'}[$__rate_interval])",
       "legendFormat": "Write Misses"
      }
     ]
    }
   ]
  },
  {
   "title": "内存: $hrMemoryDescr - ($Device)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "repeat": "hrMemoryDescr",
   "collapsed": true,
   "panels": [
    {
     "title": "内存大小",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 190 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hrStorageSize{job=~'$JobName',instance=~'$Device',hrStorageDescr=~'$hrMemoryDescr'} * hrStorageAllocationUnits{job=~'$JobName',instance=~'$Device',hrStorageDescr=~'$hrMemoryDescr'}"
      }
     ]
    },
    {
     "title": "内存使用情况: $hrMemoryDescr ($Device)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 21, "x": 3, "y": 190 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "hrStorageSize{job=~'$JobName',instance=~'$Device',hrStorageDescr=~'$hrMemoryDescr'} * hrStorageAllocationUnits{job=~'$JobName',instance=~'$Device',hrStorageDescr=~'$hrMemoryDescr'}",
       "legendFormat": "Size"
      },
      {
       "expr": "hrStorageUsed{job=~'$JobName',instance=~'$Device',hrStorageDescr=~'$hrMemoryDescr'} * hrStorageAllocationUnits{job=~'$JobName',instance=~'$Device',hrStorageDescr=~'$hrMemoryDescr'}",
       "legendFormat": "Used"
      },
      {
       "expr": "(hrStorageSize{job=~'$JobName',instance=~'$Device',hrStorageDescr=~'$hrMemoryDescr'} -  hrStorageUsed{job=~'$JobName',instance=~'$Device',hrStorageDescr=~'$hrMemoryDescr'}) * hrStorageAllocationUnits{job=~'$JobName',instance=~'$Device',hrStorageDescr=~'$hrMemoryDescr'}\n",
       "legendFormat": "Free"
      }
     ]
    },
    {
     "title": "已用大小百分比",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 194 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(hrStorageUsed{job=~'$JobName',instance=~'$Device',hrStorageDescr=~'$hrMemoryDescr'} /hrStorageSize{job=~'$JobName',instance=~'$Device',hrStorageDescr=~'$hrMemoryDescr'})*100",
       "legendFormat": "% Used"
      }
     ]
    }
   ]
  },
  {
   "title": "网络接口: ($Interface) - ($Device)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "repeat": "Interface",
   "collapsed": true,
   "panels": [
    {
     "title": "接口详细: $Interface - ($Device)",
     "type": "table",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 265 },
     "targets": [
      {
       "expr": "ifPhysAddress{job=~'$JobName',instance=~'$Device',ifName=~'$Interface'}"
      },
      {
       "expr": "ifAdminStatus{job=~'$JobName',instance=~'$Device',ifName=~'$Interface'}"
      },
      {
       "expr": "ifConnectorPresent{job=~'$JobName',instance=~'$Device',ifName=~'$Interface'}"
      },
      {
       "expr": "ifHighSpeed{job=~'$JobName',instance=~'$Device',ifName=~'$Interface'}"
      },
      {
       "expr": "ifOperStatus{job=~'$JobName',instance=~'$Device',ifName=~'$Interface'}"
      },
      {
       "expr": "ifMtu{job=~'$JobName',instance=~'$Device',ifName=~'$Interface'}"
      }
     ]
    },
    {
     "title": "接口流量: $Interface - ($Device)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 269 },
     "fieldConfig": { "defaults": { "unit": "decbits" } },
     "targets": [
      {
       "expr": "rate(ifHCInOctets{job=~'$JobName',instance=~'$Device',ifName=~'$Interface'}[$__rate_interval]) * $interfacebits",
       "legendFormat": "Traffic In"
      },
      {
       "expr": "rate(ifHCOutOctets{job=~'$JobName',instance=~'$Device',ifName=~'$Interface'}[$__rate_interval]) * $interfacebits",
       "legendFormat": "Traffic Out"
      }
     ]
    },
    {
     "title": "多播 & 广播: $Interface - ($Device)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 277 },
     "fieldConfig": { "defaults": { "unit": "decbits" } },
     "targets": [
      {
       "expr": "rate(ifInBroadcastPkts{job=~'$JobName',instance=~'$Device',ifName=~'$Interface'}[$__rate_interval]) * $interfacebits",
       "legendFormat": "Broadcast In"
      },
      {
       "expr": "rate(ifOutBroadcastPkts{job=~'$JobName',instance=~'$Device',ifName=~'$Interface'}[$__rate_interval]) * $interfacebits",
       "legendFormat": "Broadcast  Out"
      },
      {
       "expr": "rate(ifInMulticastPkts{job=~'$JobName',instance=~'$Device',ifName=~'$Interface'}[$__rate_interval]) * $interfacebits",
       "legendFormat": "Multicast  In"
      },
      {
       "expr": "rate(ifOutMulticastPkts{job=~'$JobName',instance=~'$Device',ifName=~'$Interface'}[$__rate_interval]) * $interfacebits",
       "legendFormat": "Multicast  Out"
      }
     ]
    },
    {
     "title": "丢包 & 错包 $Interface: - ($Device)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 277 },
     "targets": [
      {
       "expr": "rate(ifInDiscards{job=~'$JobName',instance=~'$Device',ifName=~'$Interface'}[$__rate_interval])",
       "legendFormat": "Discards In"
      },
      {
       "expr": "rate(ifInErrors{job=~'$JobName',instance=~'$Device',ifName=~'$Interface'}[$__rate_interval])",
       "legendFormat": "Errors In"
      },
      {
       "expr": "rate(ifOutDiscards{job=~'$JobName',instance=~'$Device',ifName=~'$Interface'}[$__rate_interval])",
       "legendFormat": "Discards Out"
      },
      {
       "expr": "rate(ifOutErrors{job=~'$JobName',instance=~'$Device',ifName=~'$Interface'}[$__rate_interval])",
       "legendFormat": "Errors Out"
      }
     ]
    }
   ]
  },
  {
   "title": "Volume: $spaceIODevice - ($Device)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "repeat": "spaceIODevice",
   "collapsed": true,
   "panels": [
    {
     "title": "Volume 吞吐量 - $spaceIODevice ($Device)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 309 },
     "targets": [
      {
       "expr": "rate(spaceIONReadX{job=~'$JobName',instance=~'$Device',spaceIODevice=~'$spaceIODevice'}[$__rate_interval])",
       "legendFormat": "Read Bytes"
      },
      {
       "expr": "rate(spaceIONWrittenX{job=~'$JobName',instance=~'$Device',spaceIODevice=~'$spaceIODevice'}[$__rate_interval])",
       "legendFormat": "Written Bytes"
      }
     ]
    },
    {
     "title": "Volume IOPS - $spaceIODevice ($Device)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 309 },
     "targets": [
      {
       "expr": "rate(spaceIOReads{job=~'$JobName',instance=~'$Device',spaceIODevice=~'$spaceIODevice'}[$__rate_interval])",
       "legendFormat": "Read Bytes"
      },
      {
       "expr": "rate(spaceIOWrites{job=~'$JobName',instance=~'$Device',spaceIODevice=~'$spaceIODevice'}[$__rate_interval])",
       "legendFormat": "Written Bytes"
      }
     ]
    }
   ]
  },
  {
   "title": "SMART - ($SmartDev)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "repeat": "SmartDev",
   "collapsed": true,
   "panels": [
    {
     "title": "S.M.A.R.T ",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 382 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(diskSMARTInfoDevName{job=~'$JobName',instance=~'$Device',diskSMARTInfoDevName=~'$SmartDev'})",
       "legendFormat": "SMART Checks"
      }
     ]
    },
    {
     "title": "S.M.A.R.T: $SmartDev (Data is from the last time the Scheduled task was run)",
     "type": "table",
     "gridPos": { "h": 8, "w": 21, "x": 3, "y": 382 },
     "targets": [
      {
       "expr": "diskSMARTInfoDevName{job=~'$JobName',instance=~'$Device',diskSMARTInfoDevName='$SmartDev'}",
       "legendFormat": "SMARTInfo"
      },
      {
       "expr": "diskSMARTAttrName{job=~'$JobName',instance=~'$Device'}",
       "legendFormat": "AttrName"
      },
      {
       "expr": "diskSMARTAttrCurrent{job=~'$JobName',instance=~'$Device'}",
       "legendFormat": "AttrCurrent"
      },
      {
       "expr": "diskSMARTAttrThreshold{job=~'$JobName',instance=~'$Device'}",
       "legendFormat": "AttrThreshold"
      },
      {
       "expr": "diskSMARTAttrWorst{job=~'$JobName',instance=~'$Device'}",
       "legendFormat": "AttrWorst"
      },
      {
       "expr": "diskSMARTAttrStatus{job=~'$JobName',instance=~'$Device'}",
       "legendFormat": "AttrStatus"
      },
      {
       "expr": "diskSMARTAttrRaw{job=~'$JobName',instance=~'$Device'}",
       "legendFormat": "AttrRaw"
      }
     ]
    },
    {
     "title": "S.M.A.R.T: $SmartDev",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 386 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "diskSMARTInfoDevName{job=~'$JobName',instance=~'$Device',diskSMARTInfoDevName=~'$SmartDev'}",
       "legendFormat": "diskSMARTInfoDevName"
      },
      {
       "expr": "diskSMARTAttrStatus{job=~'$JobName',instance=~'$Device',diskSMARTAttrStatus!=\"OK\"}",
       "legendFormat": "diskSMARTAttrStatus"
      }
     ]
    }
   ]
  }
 ]
}