global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'codelab-monitor'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus-server'
    scrape_interval: 5s			    # Override the global default and scrape targets from this job every 5 seconds.
    static_configs:
      - targets: ['prometheus-server:9090']
    basic_auth:
      username: "admin"
      password: "test"

  - job_name: DS1522-node
    static_configs:
      - targets: ['prometheus-node:9100']	

  - job_name: SNMP			# https://colby.gg/posts/2023-10-17-monitoring-synology/
    static_configs:	
      - targets:			# SNMP devices list
         - dsm.lab				
    metrics_path: /snmp
    params:
      auth: [snmpv3]
      module: [if_mib, synology]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - source_labels: [__param_target]
        regex: (.*)
        replacement: prometheus-snmp:9116	# replacement: ${1}:9116
        target_label: __address__

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: [ 'prometheus-alert:9093' ]

rule_files:
  - rules.yaml
