---
apiVersion: v1
kind: Secret
metadata:
  name: admin-password
  namespace: mongodb
type: Opaque
stringData:
  password: superSecretPassword123

---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb-replset
  namespace: mongodb
  labels:
    app: mongodb
    role: backend
spec:
  members: 3
  type: ReplicaSet
  version: "7.0.25"

  security:
    authentication:
      modes: ["SCRAM"]

  users:
    - name: admin
      db: admin
      passwordSecretRef:
        name: admin-password
        key: password
      roles:
        - name: root
          db: admin
      scramCredentialsSecretName: my-scram

  statefulSet:
    spec:
      serviceName: "mongodb-replset"
      podManagementPolicy: Parallel
      updateStrategy:
        type: RollingUpdate

      template:
        spec:
          containers:
            - name: mongod
              resources:
                requests:
                  cpu: "500m"
                  memory: "1Gi"
                limits:
                  cpu: "1"
                  memory: "2Gi"

              # Mount existing PVC paths
              volumeMounts:
                - name: data-volume
                  mountPath: /data
                - name: logs-volume
                  mountPath: /var/log/mongodb

          volumes:
            - name: data-volume
              persistentVolumeClaim:
                claimName: data-volume-$(STATEFULSET_NAME)-$(POD_INDEX)
            - name: logs-volume
              persistentVolumeClaim:
                claimName: logs-volume-$(STATEFULSET_NAME)-$(POD_INDEX)

  additionalMongodConfig:
    net:
      port: 27017
