# https://github.com/opf/openproject-deploy/blob/stable/13/compose/docker-compose.yml
# Modified for Kube-env

version: "3.7"

networks:
  network_macvlan:
    name: network00
    external: true
  backend:
    name: openproject_network
    driver: bridge

x-op-restart-policy: &restart_policy
  restart: unless-stopped
x-op-image: &image
  image: openproject/community:13
x-op-app: &app
  <<: [*image, *restart_policy]
  environment:
    OPENPROJECT_HTTPS: "false"
    OPENPROJECT_HOST__NAME: "openproject.lab"
    OPENPROJECT_HSTS: "true"
    RAILS_CACHE_STORE: "memcache"
    OPENPROJECT_CACHE__MEMCACHE__SERVER: "cache:11211"
    OPENPROJECT_RAILS__RELATIVE__URL__ROOT: ""
    DATABASE_URL: "postgres://postgres:p4ssw0rd@db/openproject?pool=20&encoding=unicode&reconnect=true"
    RAILS_MIN_THREADS: 4
    RAILS_MAX_THREADS: 16
    # set to true to enable the email receiving feature. See ./docker/cron for more options
    IMAP_ENABLED: "false}"
  volumes:
    - ./opdata:/var/openproject/assets

services:
  db:
    image: postgres:13
    <<: *restart_policy
    container_name: openproject-db
    stop_grace_period: "3s"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: p4ssw0rd
      POSTGRES_DB: openproject
    networks:
      - backend

  cache:
    image: memcached
    <<: *restart_policy
    container_name: openproject-cache
    networks:
      - backend

  proxy:
    <<: [*image, *restart_policy]
    container_name: openproject-proxy
    command: "./docker/prod/proxy"
    ports:
      - 80/tcp
    environment:
      APP_HOST: openproject-web
      OPENPROJECT_RAILS__RELATIVE__URL__ROOT: ""
    depends_on:
      - web
    networks:
      network_macvlan: 
        ipv4_address: 192.168.0.27
      backend:

  web:
    <<: *app
    container_name: openproject-web
    command: "./docker/prod/web"
    networks:
      backend:
    depends_on:
      - db
      - cache
      - seeder
    labels:
      - autoheal=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health_checks/default"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s

  autoheal:
    image: willfarrell/autoheal:1.2.0
    container_name: openproject-autoheal
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      AUTOHEAL_CONTAINER_LABEL: autoheal
      AUTOHEAL_START_PERIOD: 600
      AUTOHEAL_INTERVAL: 30

  worker:
    <<: *app
    container_name: openproject-worker
    command: "./docker/prod/worker"
    networks:
      - backend
    depends_on:
      - db
      - cache
      - seeder

  cron:
    <<: *app
    container_name: openproject-cron
    command: "./docker/prod/cron"
    networks:
      - backend
    depends_on:
      - db
      - cache
      - seeder

  seeder:
    <<: *app
    container_name: openproject-seeder
    command: "./docker/prod/seeder"
    restart: on-failure
    networks:
      - backend

